.github/CODEOWNERS

add CODEOWNER file

---

.github/workflows/backendTest.yml
eWiLL_backend/docker-compose.yml

Added backend test workflow action

---

eWiLL_frontend/package-lock.json
eWiLL_frontend/package.json
eWiLL_frontend/src/App.vue
eWiLL_frontend/src/assets/settings.scss
eWiLL_frontend/src/main.js
eWiLL_frontend/src/plugins/index.js
eWiLL_frontend/src/plugins/vuetify.js
eWiLL_frontend/src/plugins/webfontloader.js
eWiLL_frontend/src/views/ViewModelling.vue
eWiLL_frontend/vite.config.js

add Vuetify to Project

---

eWiLL_frontend/package-lock.json
eWiLL_frontend/package.json
eWiLL_frontend/src/App.vue
eWiLL_frontend/src/assets/settings.scss
eWiLL_frontend/src/main.js
eWiLL_frontend/src/plugins/index.js
eWiLL_frontend/src/plugins/vuetify.js
eWiLL_frontend/src/plugins/webfontloader.js
eWiLL_frontend/src/views/ViewModelling.vue
eWiLL_frontend/vite.config.js

Merge vuetify into branch 31-create-loginlogout

add Vuetify to Project (#33)

---

eWiLL_frontend/src/App.vue
eWiLL_frontend/src/components/DropdownUserNav.vue
eWiLL_frontend/src/router/index.js
eWiLL_frontend/src/views/ViewHome.vue
eWiLL_frontend/src/views/ViewLogin.vue
eWiLL_frontend/src/views/ViewProfile.vue

frontend is now fully protected with auth

---

eWiLL_checker/Hallo.txt

ad new text

---

eWiLL_frontend/src/components/Entity.vue
eWiLL_frontend/src/components/Line.vue
eWiLL_frontend/src/components/ModalAddAttributes.vue
eWiLL_frontend/src/views/ViewModelling.vue

adjust model tool to vuetify an fix bugs

---

eWiLL_frontend/src/components/Entity.vue
eWiLL_frontend/src/components/IncomingAnkerPoint.vue
eWiLL_frontend/src/components/OutgoingAnkerPoint.vue
eWiLL_frontend/src/views/ViewModelling.vue

50 adjustment of the data structure

---

eWiLL_frontend/src/components/EntityMain.vue
eWiLL_frontend/src/components/EntityWidget.vue
eWiLL_frontend/src/components/LineMain.vue
eWiLL_frontend/src/components/LineWidget.vue
eWiLL_frontend/src/components/ModalAddAttributes.vue
eWiLL_frontend/src/stores/diagramStore.ts
eWiLL_frontend/src/stores/toolManagementStore.ts
eWiLL_frontend/src/views/ViewModelling.vue

add state management to modelling tool

---

eWiLL_frontend/src/components/EntityMain.vue
eWiLL_frontend/src/components/EntityWidget.vue
eWiLL_frontend/src/components/LineMain.vue
eWiLL_frontend/src/stores/toolManagementStore.ts
eWiLL_frontend/src/views/ViewModelling.vue

improve usability

---

eWiLL_frontend/src/components/ModelingTool.vue
eWiLL_frontend/src/components/modelingTool/EntityMain.vue
eWiLL_frontend/src/components/modelingTool/IncomingAnkerPoint.vue
eWiLL_frontend/src/components/modelingTool/OutgoingAnkerPoint.vue
eWiLL_frontend/src/stores/diagramStore.ts
eWiLL_frontend/src/stores/toolManagementStore.ts

improve UI & UX for entity connectins

---

eWiLL_backend/src/main/kotlin/com/wipdev/eWiLL_backend/database/tables/course/Course.kt
eWiLL_backend/src/main/kotlin/com/wipdev/eWiLL_backend/database/tables/course/Semester.kt
eWiLL_backend/src/main/kotlin/com/wipdev/eWiLL_backend/endpoints/RulesetController.kt
eWiLL_backend/src/main/kotlin/com/wipdev/eWiLL_backend/endpoints/SemesterController.kt
eWiLL_backend/src/main/kotlin/com/wipdev/eWiLL_backend/repository/SemesterRepository.kt
eWiLL_backend/src/main/kotlin/com/wipdev/eWiLL_backend/services/ISemesterService.kt
eWiLL_backend/src/main/kotlin/com/wipdev/eWiLL_backend/services/SemesterService.kt
eWiLL_backend/src/main/resources/data.sql

Changed ruleset path to api/ruleset
Added semester_id to courses and removed start and end date attributes from it

Added Semester object and added routes for it

---

modules/core/api/pom.xml
modules/core/api/src/main/kotlin/com/wipdev/eWiLL_backend/database/tables/Role.kt
modules/core/api/src/main/kotlin/com/wipdev/eWiLL_backend/database/tables/User.kt
modules/core/api/src/main/kotlin/com/wipdev/eWiLL_backend/endpoints/AuthController.kt
modules/core/api/src/main/kotlin/com/wipdev/eWiLL_backend/endpoints/RulesetController.kt
modules/core/api/src/main/kotlin/com/wipdev/eWiLL_backend/fbs/FbsClient.kt
modules/core/api/src/main/kotlin/com/wipdev/eWiLL_backend/repository/RoleRepository.kt
modules/core/api/src/main/kotlin/com/wipdev/eWiLL_backend/security/WebSecurityConfig.kt
modules/core/api/src/main/kotlin/com/wipdev/eWiLL_backend/security/auth/JwtUtils.kt
modules/core/api/src/main/kotlin/com/wipdev/eWiLL_backend/security/auth/UserDetailsImpl.kt
modules/core/api/src/main/kotlin/com/wipdev/eWiLL_backend/services/CourseService.kt
modules/core/api/src/main/kotlin/com/wipdev/eWiLL_backend/services/DiagramService.kt
modules/core/api/src/main/resources/data.sql
modules/core/api/src/test/kotlin/com/wipdev/eWiLL_backend/EWiLlBackendApplicationTests.kt

102 implement login from feedbacksystem

---

modules/core/web/package-lock.json
modules/core/web/package.json
modules/core/web/src/components/FileExplorer.vue
modules/core/web/src/components/ModelingTool.vue
modules/core/web/src/components/modelingTool/EntityMain.vue
modules/core/web/src/components/modelingTool/LineMain.vue
modules/core/web/src/dialog/DialogExportDiagram.vue
modules/core/web/src/stores/toolManagementStore.ts
modules/core/web/tsconfig.json

add export option for diagrams

---

modules/core/web/src/components/FileExplorer.vue
modules/core/web/src/dialog/DialogAddCategory.vue
modules/core/web/src/dialog/DialogEditTask.vue
modules/core/web/src/dialog/DialogExportDiagram.vue
modules/core/web/src/dialog/DialogSaveDiagram.vue
modules/core/web/src/model/diagram/Diagram.ts
modules/core/web/src/views/ViewTask.vue

Rename to Ordner

---

modules/core/web/src/components/ModelingTool.vue
modules/core/web/src/components/modelingTool/EntityMain.vue
modules/core/web/src/components/modelingTool/EntityWidget.vue
modules/core/web/src/components/modelingTool/LineMain.vue
modules/core/web/src/components/modelingTool/LineWidget.vue

improve change type in modelling tool

---

modules/core/web/src/views/ViewModeling.vue

prevent exit

---

modules/core/api/src/main/kotlin/com/wipdev/eWiLL_backend/endpoints/PythonEvaluationController.kt
modules/core/api/src/main/kotlin/com/wipdev/eWiLL_backend/eval/py/PythonEvaluationService.kt

Closes #210 
Check PythonEvaluationService.kt for a entry point to the new evaluation

Created PythonEvaluationService and Controller

---

modules/core/api/src/main/kotlin/com/wipdev/eWiLL_backend/endpoints/CourseController.kt

* Update HomeController.kt
* TestCommit

224 a commit to test the master branch (#227)

---

modules/core/api/pom.xml
modules/core/api/src/main/kotlin/com/wipdev/eWiLL_backend/endpoints/payload/requests/Attribute.kt
modules/core/api/src/main/kotlin/com/wipdev/eWiLL_backend/eval/rules/attributeequivalence/AttributeEquivalenceEvaluator.kt
modules/core/api/src/main/kotlin/com/wipdev/eWiLL_backend/services/DiagramService.kt
modules/core/api/src/main/kotlin/com/wipdev/eWiLL_backend/services/serviceInterfaces/IDiagramService.kt
modules/core/api/src/main/kotlin/com/wipdev/eWiLL_backend/utils/DBUpdateConfig.kt
modules/core/api/src/main/resources/application.properties
modules/core/web/src/components/modelingTool/EntityMain.vue
modules/core/web/src/dialog/DialogAddAttributes.vue
modules/core/web/src/enums/AttributeType.ts
modules/core/web/src/model/diagram/Attribute.ts

214 refactor attribute editor

---

modules/core/web/src/dialog/DialogAddAttributes.vue

prevent enter in form

---

modules/core/api/src/main/kotlin/com/wipdev/eWiLL_backend/utils/fbs/FbsClient.kt
modules/core/web/src/services/auth.service.ts

Removed unnecessary api call, to get the ip adress and get it from the request in backend

---

modules/core/web/src/dialog/DialogCreateCourse.vue
modules/core/web/src/dialog/DialogEditTask.vue
modules/core/web/src/dialog/DialogSaveDiagram.vue

adding progress spinner to the 'aufgabe'-dialogues

---

modules/core/api/src/main/kotlin/com/wipdev/eWiLL_backend/eval/py/PythonEvaluationService.kt

Added prepareEntityAndAttributeNames method

---

modules/core/web/src/dialog/DialogCompatibilityIssue.vue
modules/core/web/src/views/ViewLogin.vue

243 restrict access to specific browsers and devices due to compatibility issues

---

Dokumente/Models/Diagram_v1.drawio
Dokumente/Models/Diagram_v2.drawio
Dokumente/Models/Diagram_v3.drawio
Dokumente/Models/Diagram_v4.drawio
Dokumente/Models/Test.drawio

development of a generally diagram structure

---

modules/core/web/src/components/CoursesList.vue
modules/core/web/src/dialog/DialogCreateCourse.vue
modules/core/web/src/model/Semester.ts

fix table rows

---

modules/core/web/package-lock.json
modules/core/web/src/App.vue
modules/core/web/src/components/BreadCrumb.vue
modules/core/web/src/components/layout/FooterMain.vue
modules/core/web/src/components/layout/HeaderMain.vue
modules/core/web/src/components/modelingTool/DropdownUserNav.vue
modules/core/web/src/dialog/DialogCompatibilityIssue.vue
modules/core/web/src/stores/pageSettingsStore.ts
modules/core/web/src/views/ViewLogin.vue

refactor layout

---

modules/core/api/src/main/kotlin/com/wipdev/eWiLL_backend/endpoints/AuthController.kt
modules/core/api/src/main/kotlin/com/wipdev/eWiLL_backend/utils/fbs/FbsClient.kt
modules/core/api/src/main/resources/application.properties

feat(ewill): make fbs url configurable
